export const words = {
  the: {
    partOfSpeech: 'article',
    OECrank: '1',
    COCArank: '1',
    level: 'Pre-primer',
    polysemy: '12',
    part_of_speech: 'article',
    definition: 'used to refer to specific things',
    frequency: 1,
    pos: ['article'],
  },
  of: {
    partOfSpeech: 'preposition',
    OECrank: '4',
    COCArank: '4',
    level: 'Grade 1',
    polysemy: '12',
    word: 'of',
    part_of_speech: 'preposition',
    definition: 'belonging to; relating to',
    frequency: 2,
    pos: ['preposition'],
  },
  and: {
    partOfSpeech: 'coordinator',
    OECrank: '5',
    COCArank: '3',
    level: 'Pre-primer',
    polysemy: '16',
    word: 'and',
    part_of_speech: 'conjunction',
    definition: 'used to connect words or phrases',
    frequency: 3,
    pos: ['coordinator', 'conjunction'],
  },
  a: {
    partOfSpeech: 'article',
    OECrank: '6',
    COCArank: '5',
    level: 'Pre-primer',
    polysemy: '20',
    word: 'a',
    part_of_speech: 'article',
    definition: 'used before a noun to mean one',
    frequency: 4,
    pos: ['article'],
  },
  to: {
    partOfSpeech: 'preposition',
    OECrank: '3',
    COCArank: '7, 9',
    level: 'Pre-primer',
    polysemy: '17',
    word: 'to',
    part_of_speech: 'preposition',
    definition: 'indicating direction or purpose',
    frequency: 5,
    pos: ['preposition'],
  },
  in: {
    partOfSpeech: 'preposition',
    OECrank: '7',
    COCArank: '6, 128, 3038',
    level: 'Pre-primer',
    polysemy: '23',
    word: 'in',
    part_of_speech: 'preposition',
    definition: 'inside or within something',
    frequency: 6,
    pos: ['preposition'],
  },
  is: {
    word: 'is',
    part_of_speech: 'verb',
    definition: "third person singular of 'be'",
    frequency: 7,
    pos: ['verb'],
    level: '',
  },
  you: {
    partOfSpeech: 'pronoun',
    OECrank: '18',
    COCArank: '14',
    level: 'Pre-primer',
    polysemy: '9',
    word: 'you',
    part_of_speech: 'pronoun',
    definition: 'used to refer to the person spoken to',
    frequency: 8,
    pos: ['pronoun'],
  },
  that: {
    partOfSpeech: 'subordinator, determiner',
    OECrank: '8',
    COCArank: '12, 27, 903',
    level: 'Primer',
    polysemy: '17',
    word: 'that',
    part_of_speech: 'conjunction',
    definition: 'introducing a clause or statement',
    frequency: 9,
    pos: ['subordinator', 'determiner', 'conjunction'],
  },
  it: {
    partOfSpeech: 'pronoun',
    OECrank: '11',
    COCArank: '10',
    level: 'Pre-primer',
    polysemy: '18',
    word: 'it',
    part_of_speech: 'pronoun',
    definition: 'used to refer to a thing',
    frequency: 10,
    pos: ['pronoun'],
  },
  he: {
    partOfSpeech: 'pronoun',
    OECrank: '16',
    COCArank: '15',
    level: 'Primer',
    polysemy: '7',
    word: 'he',
    part_of_speech: 'pronoun',
    definition: 'used to refer to a male person',
    frequency: 11,
    pos: ['pronoun'],
  },
  was: {
    word: 'was',
    part_of_speech: 'verb',
    definition: "past tense of 'be'",
    frequency: 12,
    pos: ['verb'],
    level: '',
  },
  for: {
    partOfSpeech: 'preposition',
    OECrank: '12',
    COCArank: '13, 2339',
    level: 'Pre-primer',
    polysemy: '19',
    word: 'for',
    part_of_speech: 'preposition',
    definition: 'indicating purpose or recipient',
    frequency: 13,
    pos: ['preposition'],
  },
  on: {
    partOfSpeech: 'preposition',
    OECrank: '14',
    COCArank: '17, 155',
    level: 'Primer',
    polysemy: '43',
    word: 'on',
    part_of_speech: 'preposition',
    definition: 'positioned above or supported by',
    frequency: 14,
    pos: ['preposition'],
  },
  are: {
    word: 'are',
    part_of_speech: 'verb',
    definition: "present tense plural of 'be'",
    frequency: 15,
    pos: ['verb'],
    level: '',
  },
  as: {
    partOfSpeech: 'adverb, preposition',
    OECrank: '17',
    COCArank: '33, 49, 129',
    level: 'Grade 1',
    polysemy: '17',
    word: 'as',
    part_of_speech: 'conjunction',
    definition: 'used to indicate similarity or reason',
    frequency: 16,
    pos: ['adverb', 'preposition', 'conjunction'],
  },
  with: {
    partOfSpeech: 'preposition',
    OECrank: '15',
    COCArank: '16',
    level: 'Primer',
    polysemy: '11',
    word: 'with',
    part_of_speech: 'preposition',
    definition: 'accompanied by someone or something',
    frequency: 17,
    pos: ['preposition'],
  },
  his: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '23',
    COCArank: '25, 1887',
    level: 'Grade 1',
    polysemy: '6',
    word: 'his',
    part_of_speech: 'pronoun',
    definition: 'belonging to a male person',
    frequency: 18,
    pos: ['possessive pronoun', 'pronoun'],
  },
  they: {
    partOfSpeech: 'pronoun',
    OECrank: '26',
    COCArank: '21',
    level: 'Primer',
    polysemy: '6',
    word: 'they',
    part_of_speech: 'pronoun',
    definition: 'used to refer to a group of people or things',
    frequency: 19,
    pos: ['pronoun'],
  },
  I: {
    partOfSpeech: 'pronoun',
    OECrank: '10',
    COCArank: '11',
    level: 'Pre-primer',
    polysemy: '7',
    word: 'I',
    part_of_speech: 'pronoun',
    definition: 'used by the speaker to refer to themselves',
    frequency: 20,
    pos: ['pronoun'],
  },
  at: {
    partOfSpeech: 'preposition',
    OECrank: '20',
    COCArank: '22',
    level: 'Primer',
    polysemy: '14',
    word: 'at',
    part_of_speech: 'preposition',
    definition: 'indicating a point or position',
    frequency: 21,
    pos: ['preposition'],
  },
  be: {
    partOfSpeech: 'verb',
    OECrank: '2',
    COCArank: '2',
    level: 'Primer',
    polysemy: '21',
    word: 'be',
    part_of_speech: 'verb',
    definition: 'to exist or live',
    frequency: 22,
    pos: ['verb'],
  },
  this: {
    partOfSpeech: 'determiner, adverb, noun',
    OECrank: '21',
    COCArank: '20, 4665',
    level: 'Primer',
    polysemy: '9',
    word: 'this',
    part_of_speech: 'pronoun',
    definition: 'used to identify a specific thing',
    frequency: 23,
    pos: ['determiner', 'adverb', 'noun', 'pronoun'],
  },
  have: {
    partOfSpeech: 'verb',
    OECrank: '9',
    COCArank: '8',
    level: 'Primer',
    polysemy: '25',
    word: 'have',
    part_of_speech: 'verb',
    definition: 'to possess, own, or hold',
    frequency: 24,
    pos: ['verb'],
  },
  from: {
    partOfSpeech: 'preposition',
    OECrank: '25',
    COCArank: '26',
    level: 'Grade 1',
    polysemy: '4',
    word: 'from',
    part_of_speech: 'preposition',
    definition: 'indicating a starting point',
    frequency: 25,
    pos: ['preposition'],
  },
  or: {
    partOfSpeech: 'coordinator',
    OECrank: '31',
    COCArank: '32',
    level: 'Grade 2',
    polysemy: '11',
    word: 'or',
    part_of_speech: 'conjunction',
    definition: 'used to connect alternatives',
    frequency: 26,
    pos: ['coordinator', 'conjunction'],
  },
  one: {
    partOfSpeech: 'noun, adjective, et al.',
    OECrank: '35',
    COCArank: '51, 104, 839',
    level: 'Pre-primer',
    polysemy: '24',
    word: 'one',
    part_of_speech: 'number',
    definition: 'the number 1',
    frequency: 27,
    pos: ['noun', 'adjective', 'number'],
  },
  had: {
    word: 'had',
    part_of_speech: 'verb',
    definition: "past tense of 'have'",
    frequency: 28,
    pos: ['verb'],
    level: '',
  },
  by: {
    partOfSpeech: 'preposition',
    OECrank: '24',
    COCArank: '30, 1190',
    level: 'Grade 1',
    polysemy: '19',
    word: 'by',
    part_of_speech: 'preposition',
    definition: 'indicating proximity or agency',
    frequency: 29,
    pos: ['preposition'],
  },
  word: {
    word: 'word',
    part_of_speech: 'noun',
    definition: 'a single distinct element of speech or writing',
    frequency: 30,
    pos: ['noun'],
    level: '',
  },
  but: {
    partOfSpeech: 'preposition, adverb, coordinator',
    OECrank: '22',
    COCArank: '23, 1715',
    level: 'Primer',
    polysemy: '17',
    word: 'but',
    part_of_speech: 'conjunction',
    definition: 'used to introduce contrast',
    frequency: 31,
    pos: ['preposition', 'adverb', 'coordinator', 'conjunction'],
  },
  not: {
    partOfSpeech: 'adverb et al.',
    OECrank: '13',
    COCArank: '28, 2929',
    level: 'Pre-primer',
    polysemy: '5',
    word: 'not',
    part_of_speech: 'adverb',
    definition: 'used to negate a statement',
    frequency: 32,
    pos: ['adverb'],
  },
  what: {
    partOfSpeech: 'pronoun, adverb, et al.',
    OECrank: '40',
    COCArank: '34',
    level: 'Primer',
    polysemy: '19',
    word: 'what',
    part_of_speech: 'pronoun',
    definition: 'asking for information',
    frequency: 33,
    pos: ['pronoun', 'adverb'],
  },
  all: {
    partOfSpeech: 'adjective',
    OECrank: '36',
    COCArank: '43, 222',
    level: 'Primer',
    polysemy: '15',
    word: 'all',
    part_of_speech: 'adjective',
    definition: 'the whole amount',
    frequency: 34,
    pos: ['adjective'],
  },
  were: {
    word: 'were',
    part_of_speech: 'verb',
    definition: "past tense plural of 'be'",
    frequency: 35,
    pos: ['verb'],
    level: '',
  },
  we: {
    partOfSpeech: 'pronoun',
    OECrank: '27',
    COCArank: '24',
    level: 'Pre-primer',
    polysemy: '6',
    word: 'we',
    part_of_speech: 'pronoun',
    definition: 'used to refer to the speaker and others',
    frequency: 36,
    pos: ['pronoun'],
  },
  when: {
    partOfSpeech: 'adverb',
    OECrank: '51',
    COCArank: '57, 136',
    level: 'Grade 1',
    polysemy: '11',
    word: 'when',
    part_of_speech: 'adverb',
    definition: 'at what time',
    frequency: 37,
    pos: ['adverb'],
  },
  your: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '64',
    COCArank: '69',
    level: 'Grade 2',
    polysemy: '4',
    word: 'your',
    part_of_speech: 'pronoun',
    definition: 'belonging to you',
    frequency: 38,
    pos: ['possessive pronoun', 'pronoun'],
  },
  can: {
    partOfSpeech: 'verb, noun',
    OECrank: '53',
    COCArank: '37, 2973',
    level: 'Pre-primer',
    polysemy: '18',
    word: 'can',
    part_of_speech: 'verb',
    definition: 'to be able to',
    frequency: 39,
    pos: ['verb', 'noun'],
  },
  said: {
    word: 'said',
    part_of_speech: 'verb',
    definition: "past tense of 'say'",
    frequency: 40,
    pos: ['verb'],
    level: '',
  },
  there: {
    partOfSpeech: 'adverb, pronoun, et al.',
    OECrank: '38',
    COCArank: '53, 116',
    level: 'Primer',
    polysemy: '14',
    word: 'there',
    part_of_speech: 'adverb',
    definition: 'in or at a place',
    frequency: 41,
    pos: ['adverb', 'pronoun'],
  },
  use: {
    partOfSpeech: 'verb, noun',
    OECrank: '83',
    COCArank: '92, 429',
    level: 'Grade 2',
    polysemy: '17',
    word: 'use',
    part_of_speech: 'verb',
    definition: 'to employ for a purpose',
    frequency: 42,
    pos: ['verb', 'noun'],
  },
  an: {
    partOfSpeech: 'article',
    OECrank: '32',
    COCArank: '(a)',
    level: 'Grade 1',
    polysemy: '6',
    word: 'an',
    part_of_speech: 'article',
    definition: 'used before nouns beginning with vowels',
    frequency: 43,
    pos: ['article'],
  },
  each: {
    word: 'each',
    part_of_speech: 'adjective',
    definition: 'every one of two or more people or things',
    frequency: 44,
    pos: ['adjective'],
    level: '',
  },
  which: {
    partOfSpeech: 'pronoun',
    OECrank: '48',
    COCArank: '58',
    level: 'Grade 2',
    polysemy: '7',
    word: 'which',
    part_of_speech: 'pronoun',
    definition: 'asking for choice or specifying',
    frequency: 45,
    pos: ['pronoun'],
  },
  she: {
    partOfSpeech: 'pronoun',
    OECrank: '30',
    COCArank: '31',
    level: 'Primer',
    polysemy: '7',
    word: 'she',
    part_of_speech: 'pronoun',
    definition: 'used to refer to a female person',
    frequency: 46,
    pos: ['pronoun'],
  },
  do: {
    partOfSpeech: 'verb, noun',
    OECrank: '19',
    COCArank: '18',
    level: 'Primer',
    polysemy: '38',
    word: 'do',
    part_of_speech: 'verb',
    definition: 'to perform or execute',
    frequency: 47,
    pos: ['verb', 'noun'],
  },
  how: {
    partOfSpeech: 'adverb',
    OECrank: '85',
    COCArank: '76',
    level: 'Grade 1',
    polysemy: '11',
    word: 'how',
    part_of_speech: 'adverb',
    definition: 'in what way or manner',
    frequency: 48,
    pos: ['adverb'],
  },
  their: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '39',
    COCArank: '36',
    level: 'Grade 2',
    polysemy: '2',
    word: 'their',
    part_of_speech: 'pronoun',
    definition: 'belonging to them',
    frequency: 49,
    pos: ['possessive pronoun', 'pronoun'],
  },
  if: {
    partOfSpeech: 'preposition',
    OECrank: '44',
    COCArank: '40',
    level: 'Grade 3',
    polysemy: '9',
    word: 'if',
    part_of_speech: 'conjunction',
    definition: 'introducing a condition',
    frequency: 50,
    pos: ['preposition', 'conjunction'],
  },
  will: {
    partOfSpeech: 'verb, noun',
    OECrank: '33',
    COCArank: '48, 1506',
    level: 'Primer',
    polysemy: '16',
    word: 'will',
    part_of_speech: 'verb',
    definition: 'used to express future intention',
    frequency: 51,
    pos: ['verb', 'noun'],
  },
  up: {
    partOfSpeech: 'adverb, preposition, et al.',
    OECrank: '42',
    COCArank: '50, 456',
    level: 'Pre-primer',
    polysemy: '50',
    word: 'up',
    part_of_speech: 'adverb',
    definition: 'toward a higher position',
    frequency: 52,
    pos: ['adverb', 'preposition'],
  },
  other: {
    partOfSpeech: 'adjective, pronoun',
    OECrank: '70',
    COCArank: '75, 715, 2355',
    level: '',
    polysemy: '12',
    word: 'other',
    part_of_speech: 'adjective',
    definition: 'different from one already mentioned',
    frequency: 53,
    pos: ['adjective', 'pronoun'],
  },
  about: {
    partOfSpeech: 'preposition, adverb, et al.',
    OECrank: '45',
    COCArank: '46, 179',
    level: 'Grade 3',
    polysemy: '18',
    word: 'about',
    part_of_speech: 'preposition',
    definition: 'on the subject of',
    frequency: 54,
    pos: ['preposition', 'adverb'],
  },
  out: {
    partOfSpeech: 'preposition',
    OECrank: '43',
    COCArank: '64, 149',
    level: 'Primer',
    polysemy: '38',
    word: 'out',
    part_of_speech: 'adverb',
    definition: 'away from the inside',
    frequency: 55,
    pos: ['preposition', 'adverb'],
  },
  many: {
    word: 'many',
    part_of_speech: 'adjective',
    definition: 'a large number',
    frequency: 56,
    pos: ['adjective'],
    level: '',
  },
  then: {
    partOfSpeech: 'adverb',
    OECrank: '72',
    COCArank: '77',
    level: 'Grade 1',
    polysemy: '10',
    word: 'then',
    part_of_speech: 'adverb',
    definition: 'at that time',
    frequency: 57,
    pos: ['adverb'],
  },
  them: {
    partOfSpeech: 'pronoun',
    OECrank: '68',
    COCArank: '59',
    level: 'Grade 1',
    polysemy: '3',
    word: 'them',
    part_of_speech: 'pronoun',
    definition: 'used to refer to other people or things',
    frequency: 58,
    pos: ['pronoun'],
  },
  these: {
    partOfSpeech: 'pronoun',
    OECrank: '96',
    COCArank: '82',
    level: 'Grade 2',
    polysemy: '2',
    word: 'these',
    part_of_speech: 'pronoun',
    definition: 'used to identify specific things',
    frequency: 59,
    pos: ['pronoun'],
  },
  so: {
    partOfSpeech: 'coordinator, adverb, et al.',
    OECrank: '41',
    COCArank: '55, 196',
    level: 'Primer',
    polysemy: '18',
    word: 'so',
    part_of_speech: 'adverb',
    definition: 'to such a great extent',
    frequency: 60,
    pos: ['coordinator', 'adverb'],
  },
  some: {
    partOfSpeech: 'determiner',
    OECrank: '66',
    COCArank: '60',
    level: 'Grade 1',
    polysemy: '10',
    word: 'some',
    part_of_speech: 'adjective',
    definition: 'an unspecified amount or number',
    frequency: 61,
    pos: ['determiner', 'adjective'],
  },
  her: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '29, 106',
    COCArank: '42',
    level: 'Grade 1',
    polysemy: '3',
    word: 'her',
    part_of_speech: 'pronoun',
    definition: 'belonging to a female person',
    frequency: 62,
    pos: ['possessive pronoun', 'pronoun'],
  },
  would: {
    partOfSpeech: 'verb',
    OECrank: '37',
    COCArank: '41',
    level: 'Grade 2',
    polysemy: '13',
    word: 'would',
    part_of_speech: 'verb',
    definition: 'indicating a possibility or condition',
    frequency: 63,
    pos: ['verb'],
  },
  make: {
    partOfSpeech: 'verb, noun',
    OECrank: '52',
    COCArank: '45',
    level: 'Grade 2',
    polysemy: '48',
    word: 'make',
    part_of_speech: 'verb',
    definition: 'to create or produce',
    frequency: 64,
    pos: ['verb', 'noun'],
  },
  like: {
    partOfSpeech: 'preposition, verb',
    OECrank: '54',
    COCArank: '74, 208, 1123, 1684, 2702',
    level: 'Primer',
    polysemy: '26',
    word: 'like',
    part_of_speech: 'preposition',
    definition: 'similar to',
    frequency: 65,
    pos: ['preposition', 'verb'],
  },
  him: {
    partOfSpeech: 'pronoun',
    OECrank: '58',
    COCArank: '68',
    level: 'Grade 1',
    polysemy: '5',
    word: 'him',
    part_of_speech: 'pronoun',
    definition: 'used to refer to a male person',
    frequency: 66,
    pos: ['pronoun'],
  },
  into: {
    partOfSpeech: 'preposition',
    OECrank: '62',
    COCArank: '65',
    level: 'Primer',
    polysemy: '10',
    word: 'into',
    part_of_speech: 'preposition',
    definition: 'to the inside of',
    frequency: 67,
    pos: ['preposition'],
  },
  time: {
    partOfSpeech: 'noun',
    OECrank: '55',
    COCArank: '52',
    level: 'Dolch list of 95 nouns',
    polysemy: '14',
    word: 'time',
    part_of_speech: 'noun',
    definition: 'a measurable period',
    frequency: 68,
    pos: ['noun'],
  },
  has: {
    word: 'has',
    part_of_speech: 'verb',
    definition: "third person singular of 'have'",
    frequency: 69,
    pos: ['verb'],
    level: '',
  },
  look: {
    partOfSpeech: 'verb',
    OECrank: '74',
    COCArank: '85, 604',
    level: 'Pre-primer',
    polysemy: '17',
    word: 'look',
    part_of_speech: 'verb',
    definition: "to direct one's eyes",
    frequency: 70,
    pos: ['verb'],
  },
  two: {
    partOfSpeech: 'noun',
    OECrank: '84',
    COCArank: '80',
    level: 'Pre-primer',
    polysemy: '6',
    word: 'two',
    part_of_speech: 'number',
    definition: 'the number 2',
    frequency: 71,
    pos: ['noun', 'number'],
  },
  more: {
    word: 'more',
    part_of_speech: 'adjective',
    definition: 'a greater amount',
    frequency: 72,
    pos: ['adjective'],
    level: '',
  },
  write: {
    word: 'write',
    part_of_speech: 'verb',
    definition: 'to form letters or words',
    frequency: 73,
    pos: ['verb'],
    level: '',
  },
  go: {
    partOfSpeech: 'verb, noun',
    OECrank: '49',
    COCArank: '35',
    level: 'Pre-primer',
    polysemy: '54',
    word: 'go',
    part_of_speech: 'verb',
    definition: 'to move or travel',
    frequency: 74,
    pos: ['verb', 'noun'],
  },
  see: {
    partOfSpeech: 'verb',
    OECrank: '69',
    COCArank: '67',
    level: '',
    polysemy: '25',
    word: 'see',
    part_of_speech: 'verb',
    definition: "to use one's eyes",
    frequency: 74,
    pos: ['verb'],
  },
  say: {
    partOfSpeech: 'verb et al.',
    OECrank: '28',
    COCArank: '19',
    level: 'Primer',
    polysemy: '17',
    pos: ['verb'],
  },
  who: {
    partOfSpeech: 'pronoun, noun',
    OECrank: '46',
    COCArank: '38',
    level: 'Primer',
    polysemy: '5',
    pos: ['pronoun', 'noun'],
  },
  get: {
    partOfSpeech: 'verb',
    OECrank: '47',
    COCArank: '39',
    level: 'Primer',
    polysemy: '37',
    pos: ['verb'],
  },
  my: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '34',
    COCArank: '44',
    level: 'Pre-primer',
    polysemy: '5',
    pos: ['possessive pronoun'],
  },
  know: {
    partOfSpeech: 'verb, noun',
    OECrank: '59',
    COCArank: '47',
    level: 'Grade 1',
    polysemy: '13',
    pos: ['verb', 'noun'],
  },
  think: {
    partOfSpeech: 'verb',
    OECrank: '79',
    COCArank: '56',
    level: 'Grade 1',
    polysemy: '10',
    pos: ['verb'],
  },
  me: {
    partOfSpeech: 'pronoun',
    OECrank: '50',
    COCArank: '61',
    level: 'Pre-primer',
    polysemy: '10',
    pos: ['pronoun'],
  },
  no: {
    partOfSpeech: 'determiner, adverb',
    OECrank: '56',
    COCArank: '93, 699, 916, 1111, 4555',
    level: 'Primer',
    polysemy: '10',
    pos: ['determiner', 'adverb'],
  },
  just: {
    partOfSpeech: 'adjective',
    OECrank: '57',
    COCArank: '66, 1823',
    level: 'Grade 1',
    polysemy: '14',
    pos: ['adjective'],
  },
  year: {
    partOfSpeech: 'noun',
    OECrank: '63',
    COCArank: '54',
    level: '',
    polysemy: '7',
    pos: ['noun'],
  },
  people: {
    partOfSpeech: 'noun',
    OECrank: '61',
    COCArank: '62',
    level: '',
    polysemy: '9',
    pos: ['noun'],
  },
  take: {
    partOfSpeech: 'verb, noun',
    OECrank: '60',
    COCArank: '63',
    level: 'Grade 1',
    polysemy: '66',
    pos: ['verb', 'noun'],
  },
  good: {
    partOfSpeech: 'adjective',
    OECrank: '65',
    COCArank: '110, 2280',
    level: 'Primer',
    polysemy: '32',
    pos: ['adjective'],
  },
  come: {
    partOfSpeech: 'verb',
    OECrank: '76',
    COCArank: '70',
    level: 'Pre-primer',
    polysemy: '20',
    pos: ['verb'],
  },
  could: {
    partOfSpeech: 'verb',
    OECrank: '67',
    COCArank: '71',
    level: 'Grade 1',
    polysemy: '6',
    pos: ['verb'],
  },
  than: {
    partOfSpeech: 'preposition',
    OECrank: '71',
    COCArank: '73, 712',
    level: '',
    polysemy: '4',
    pos: ['preposition'],
  },
  now: {
    partOfSpeech: 'preposition',
    OECrank: '73',
    COCArank: '72, 1906',
    level: 'Primer',
    polysemy: '13',
    pos: ['preposition'],
  },
  only: {
    partOfSpeech: 'adverb',
    OECrank: '75',
    COCArank: '101, 329',
    level: 'Grade 3',
    polysemy: '11',
    pos: ['adverb'],
  },
  its: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '77',
    COCArank: '78',
    level: 'Grade 2',
    polysemy: '2',
    pos: ['possessive pronoun'],
  },
  over: {
    partOfSpeech: 'preposition',
    OECrank: '78',
    COCArank: '124, 182',
    level: 'Grade 1',
    polysemy: '19',
    pos: ['preposition'],
  },
  also: {
    partOfSpeech: 'adverb',
    OECrank: '80',
    COCArank: '87',
    level: '',
    polysemy: '2',
    pos: ['adverb'],
  },
  back: {
    partOfSpeech: 'noun, adverb',
    OECrank: '81',
    COCArank: '108, 323, 1877',
    level: 'Dolch list of 95 nouns',
    polysemy: '36',
    pos: ['noun', 'adverb'],
  },
  after: {
    partOfSpeech: 'preposition',
    OECrank: '82',
    COCArank: '120, 260',
    level: 'Grade 1',
    polysemy: '14',
    pos: ['preposition'],
  },
  our: {
    partOfSpeech: 'possessive pronoun',
    OECrank: '86',
    COCArank: '79',
    level: 'Primer',
    polysemy: '3',
    pos: ['possessive pronoun'],
  },
  work: {
    partOfSpeech: 'verb, noun',
    OECrank: '87',
    COCArank: '117, 199',
    level: 'Grade 2',
    polysemy: '28',
    pos: ['verb', 'noun'],
  },
  first: {
    partOfSpeech: 'adjective',
    OECrank: '88',
    COCArank: '86, 2064',
    level: 'Grade 2',
    polysemy: '10',
    pos: ['adjective'],
  },
  well: {
    partOfSpeech: 'adverb',
    OECrank: '89',
    COCArank: '100, 644',
    level: 'Primer',
    polysemy: '30',
    pos: ['adverb'],
  },
  way: {
    partOfSpeech: 'noun, adverb',
    OECrank: '90',
    COCArank: '84, 4090',
    level: 'Dolch list of 95 nouns',
    polysemy: '16',
    pos: ['noun', 'adverb'],
  },
  even: {
    partOfSpeech: 'adjective',
    OECrank: '91',
    COCArank: '107, 484',
    level: '',
    polysemy: '23',
    pos: ['adjective'],
  },
  want: {
    partOfSpeech: 'verb',
    OECrank: '93',
    COCArank: '83',
    level: 'Primer',
    polysemy: '10',
    pos: ['verb'],
  },
  new: {
    partOfSpeech: 'adjective et al.',
    OECrank: '92',
    COCArank: '88',
    level: 'Primer',
    polysemy: '18',
    pos: ['adjective'],
  },
  because: {
    partOfSpeech: 'preposition',
    OECrank: '94',
    COCArank: '89, 509',
    level: 'Grade 2',
    polysemy: '7',
    pos: ['preposition'],
  },
  any: {
    partOfSpeech: 'pronoun',
    OECrank: '95',
    COCArank: '109, 4720',
    level: 'Grade 1',
    polysemy: '4',
    pos: ['pronoun'],
  },
  day: {
    partOfSpeech: 'noun',
    OECrank: '98',
    COCArank: '90',
    level: 'Dolch list of 95 nouns',
    polysemy: '9',
    pos: ['noun'],
  },
  give: {
    partOfSpeech: 'verb',
    OECrank: '97',
    COCArank: '98',
    level: 'Grade 1',
    polysemy: '19',
    pos: ['verb'],
  },
  most: {
    partOfSpeech: 'adverb',
    OECrank: '99',
    COCArank: '144, 187',
    level: '',
    polysemy: '12',
    pos: ['adverb'],
  },
  us: {
    partOfSpeech: 'pronoun',
    OECrank: '100',
    COCArank: '113',
    level: 'Grade 2',
    polysemy: '6',
    pos: ['pronoun'],
  },
};

export const partsOfSpeech = {
  noun: {
    description: 'Represents people, places, things, or ideas.',
    example: 'tree, book, city',
  },
  article: { description: 'Provides context to nouns.', example: 'a, an, the' },
  adjective: {
    description: 'Descriptive words that modify nouns.',
    example: 'red, cold, happy',
  },
  verb: {
    description: 'Action words or words that describe states of being.',
    example: 'run, jump, think',
  },
  preposition: {
    description: 'Indicates direction, location, or time.',
    example: 'in, on, under',
  },
  adverb: {
    description: 'Modifies verbs, adjectives, or other adverbs.',
    example: 'slowly, beautifully, loudly',
  },
  pronoun: {
    description: 'Words that stand in for nouns.',
    example: 'he, she, it, they',
  },
  conjunction: {
    description: 'Connects words, phrases, or clauses.',
    example: 'and, but, because',
  },
  interjection: {
    description: 'Expressive words that convey strong emotions.',
    example: 'wow, ouch, hurray',
  },
};

// [
//   'coordinator',
//   'subordinator',
//   'determiner',
//   'possessive pronoun',
//   'number',
// ];

export const levels = [
  'Pre-primer',
  'Primer',
  'Grade 1',
  'Grade 2',
  'Grade 3',
  'Dolch list of 95 nouns',
];
